// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcrU1TMltPI5Xx47vPX9Jz1lL0G6T6qxc',
    appId: '1:643060504140:web:3aa151d14c6ec90c9ac6e9',
    messagingSenderId: '643060504140',
    projectId: 'munishchatapp',
    authDomain: 'munishchatapp.firebaseapp.com',
    storageBucket: 'munishchatapp.appspot.com',
    measurementId: 'G-B0SEQ0VX6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKf6IcBWtWaaS3omUf9up5vVhA5eL-3Zc',
    appId: '1:643060504140:android:d3f8bf574faaefa99ac6e9',
    messagingSenderId: '643060504140',
    projectId: 'munishchatapp',
    storageBucket: 'munishchatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByhnaE899n2KPOtRCXqy4Eg-C1vETm_sM',
    appId: '1:643060504140:ios:1c969b11f206bdb99ac6e9',
    messagingSenderId: '643060504140',
    projectId: 'munishchatapp',
    storageBucket: 'munishchatapp.appspot.com',
    androidClientId: '643060504140-k6iqtvfsi9la79p3rt0redeq06662cdv.apps.googleusercontent.com',
    iosClientId: '643060504140-20rui0kuu5t2gorkacmohhnssejo7qs7.apps.googleusercontent.com',
    iosBundleId: 'com.example.munishChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByhnaE899n2KPOtRCXqy4Eg-C1vETm_sM',
    appId: '1:643060504140:ios:1a0c763403aaf71a9ac6e9',
    messagingSenderId: '643060504140',
    projectId: 'munishchatapp',
    storageBucket: 'munishchatapp.appspot.com',
    androidClientId: '643060504140-k6iqtvfsi9la79p3rt0redeq06662cdv.apps.googleusercontent.com',
    iosClientId: '643060504140-k3cbhvlkm82gdec8a4d9c116mg4fh9gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.munishChatApp.RunnerTests',
  );
}
